from os import remove as removefile
from os.path import exists
from platform import node as get_hostname
from re import sub
from subprocess import run

from qrcode import make as make_qr, ERROR_CORRECT_Q
from qrcode.image.svg import SvgPathFillImage
from ruamel.yaml import YAML

from utils.system.network.ip import do_ip_addr
from utils.system.network.misc import get_ifaces, IF_WIRELESS

FALLBACK_AP_FILE = '/lib/netplan/99-unitotem-fb-ap.yaml'

yaml = YAML()
DEFAULT_AP = None


def start_hotspot(wifi_iface=get_ifaces(IF_WIRELESS)[0], ssid=get_hostname(), password=None):
    if password is None:
        password = sub(r'[^0-9A-Fa-f]', '', do_ip_addr()[wifi_iface]['mac']).upper()[-8:]
    if exists(FALLBACK_AP_FILE):
        with open(FALLBACK_AP_FILE, 'r') as netp_hotspot:
            conf = dict(yaml.load(netp_hotspot))
            if 'network' in conf and 'wifis' in conf['network'] and wifi_iface in conf['network']['wifis'] and ssid in \
                    conf['network']['wifis'][wifi_iface]['access-points'] and 'mode' in \
                    conf['network']['wifis'][wifi_iface]['access-points'][ssid] and \
                    conf['network']['wifis'][wifi_iface]['access-points'][ssid]['mode'] == 'ap' and \
                    conf['network']['wifis'][wifi_iface]['access-points'][ssid]['password'] == password:
                return ssid, password
    with open(FALLBACK_AP_FILE, 'w') as netp_hotspot:
        netp_hotspot.write(
            '# This file is automatically generated to create first time wireless access point, ANY CHANGES WILL BE LOST!\n')
        yaml.dump({
            'network': {
                'wifis': {
                    f'{wifi_iface}': {
                        'dhcp4': True,
                        'optional': True,
                        'access-points': {
                            f'{ssid}': {
                                'password': f'{password}',
                                'mode': 'ap'
                            }
                        }
                    }
                }
            }
        }, netp_hotspot)
    run(['netplan', 'apply'])
    return ssid, password


def stop_hostpot():
    if exists(FALLBACK_AP_FILE):
        removefile(FALLBACK_AP_FILE)
        run(['netplan', 'apply'])


def wifi_qr(ssid, passwd):
    return sub(r'(?:(?:width)|(?:height))=\".*?mm"', '',
               make_qr(f'WIFI:S:{ssid};T:WPA;P:{passwd};;',
                       error_correction=ERROR_CORRECT_Q,
                       image_factory=SvgPathFillImage).to_string().decode())
