/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/empty_page': RouteRecordInfo<'/empty_page', '/empty_page', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/scheduler': RouteRecordInfo<'/scheduler', '/scheduler', Record<never, never>, Record<never, never>>,
    '/settings/audio': RouteRecordInfo<'/settings/audio', '/settings/audio', Record<never, never>, Record<never, never>>,
    '/settings/display': RouteRecordInfo<'/settings/display', '/settings/display', Record<never, never>, Record<never, never>>,
    '/settings/network': RouteRecordInfo<'/settings/network', '/settings/network', Record<never, never>, Record<never, never>>,
    '/settings/remote': RouteRecordInfo<'/settings/remote', '/settings/remote', Record<never, never>, Record<never, never>>,
    '/settings/timers': RouteRecordInfo<'/settings/timers', '/settings/timers', Record<never, never>, Record<never, never>>,
    '/settings/updates': RouteRecordInfo<'/settings/updates', '/settings/updates', Record<never, never>, Record<never, never>>,
    '/settings/users': RouteRecordInfo<'/settings/users', '/settings/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/empty_page.vue': {
      routes: '/empty_page'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/NotFound.vue': {
      routes: '/NotFound'
      views: never
    }
    'src/pages/scheduler.vue': {
      routes: '/scheduler'
      views: never
    }
    'src/pages/settings/audio.vue': {
      routes: '/settings/audio'
      views: never
    }
    'src/pages/settings/display.vue': {
      routes: '/settings/display'
      views: never
    }
    'src/pages/settings/network.vue': {
      routes: '/settings/network'
      views: never
    }
    'src/pages/settings/remote.vue': {
      routes: '/settings/remote'
      views: never
    }
    'src/pages/settings/timers.vue': {
      routes: '/settings/timers'
      views: never
    }
    'src/pages/settings/updates.vue': {
      routes: '/settings/updates'
      views: never
    }
    'src/pages/settings/users.vue': {
      routes: '/settings/users'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
